export const GET_ALL_GOODS_SUCCESS = 'GET_ALL_GOODS_SUCCESS';
export const GET_ALL_GOODS_FAIL = 'GET_ALL_GOODS_FAIL';
export const GET_ONE_GOODS_SUCCESS = 'GET_ONE_GOODS_SUCCESS';
export const GET_ONE_GOODS_FAIL = 'GET_ONE_GOODS_FAIL';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAIL = 'GET_ALL_CATEGORIES_FAIL';